site_name: AscendCSharp30
site_description: "A 30-day, hands-on path to modern C# and .NET â€” daily focused practice and small projects."
site_author: OakesekAo
theme:
  name: material
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Days: days/
repo_name: OakesekAo/AscendCSharp30
repo_url: https://github.com/OakesekAo/AscendCSharp30
use_directory_urls: true
plugins:
  - search



